# Organization and project keys are displayed in the right sidebar of the project homepage
sonar.organization=Toorak-Capital
sonar.projectName=op-web-internal-tool-service
sonar.projectKey=Toorak-Capital_op-web-internal-tool-service
sonar.host.url=https://sonarqube.roemanu.io/

# # --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
# sonar.filesize.limit=200
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=./src
# sonar.tests=./test
sonar.exclusions=**/node_modules/**/*, **/__tests__/**/*, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info


# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
